### PR TITLE
Changes the sound data size

### PR DESCRIPTION
**Pull request by deadpahn**
https://github.com/asiekierka/nitrotracker/issues/81

My C++ journey continues and after several hours I was able to figure out how to extend the recording time back to normal. This fix allows for up to 8 seconds. I tested on my Japanese DSi via sdcard slot. My guess from the looks of it when tobmic was deprecated the length was shortened. Also, the functionality was different for when HOLDING a and simply running the record by pressing B. With my change, both have a length of around 8 seconds.

WHAT WOULD BE COOL, is a check box to be able to record in 8bit and maybe make it even longer. I sometimes like to sample videogames or movie monologues for intros. 

Anyway, _this works on my machine_ lol

### CODE REVIEW

**Comment by deadpahn** [comment]
I did just notice that if I go over the 8 second limit, anything else will be truncated to merely 1 second (even if I leave it recording longer). Not sure if the window should close after the time limit, or if the buffer should keep going (adding to the sample but subtracting the beginning). I think letting the user know, and closing the window when the buffer reaches its end is fair enough.

**Comment by asiekierka** [comment]
The original value was correct. 256\*1024 = 16384\*2\*8 = 8 seconds of 16384 Hz 16-bit samples.

Something else must be broken.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/nitrotracker/commit/cfc92fefbd9bd34f9bec5dd8675a02af9661cd1d

**Comment by asiekierka** [comment]
(For longer recording than 8 seconds, might want to open a merge request.)

**Pull request closed without merging**
