### PR TITLE
Created simple website

### PR DESCRIPTION
**Pull request by gncnpk**
Created a simple website (home, about, download pages) using GitHub Actions + Github Pages.

### CODE REVIEW

**Comment by asiekierka** [comment]
This is a copy of [Tobias's site](https://web.archive.org/web/20180702092420/http://nitrotracker.tobw.net/), isn't it?

While the project itself is open source, the website probably isn't; in addition, I would not want to confuse people into thinking this fork has any kind of official blessing - it does not.

**Comment by gncnpk** [comment]
Ah, I could do one from scratch if that would be alright?

**Comment by asiekierka** [comment]
I wouldn't worry about it for now - I understand your desire to promote Nitrous, but I wouldn't want your work to go to waste, and eventually I'd like to set up a central hub for all of my projects.

Have you considered a forum thread on whichever place chiptune artists hang out at these days?

**Comment by gncnpk** [comment]
All good, thanks for letting me know! I'll close the PR.

**Pull request closed without merging**
